name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - network
    volumes:
      - DB:/var/lib/mysql
    restart: always
    tty: true

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - network
    ports:
      - 443
    volumes:
      - WordPress:/var/www/html
    restart: always
    tty: true

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - network
    volumes:
      - WordPress:/var/www/html
    restart: always
    tty: true

networks:
  network:
    driver: bridge

volumes:
  DB:
    driver_opts:
      type: local
      device: /home/jeongwok/data/db
      o: bind
  WordPress:
    driver_opts:
      type: local
      device: /home/jeongwok/data/wordpress
      o: bind
