#!/bin/sh

if [ -f /root/reset ]; then
	rm -f /etc/nginx/http.d/wordpress.conf
	rm -f /etc/ssl/private/nginx.key
	rm -f /etc/ssl/certs/nginx.crt
	cp /root/wordpress.conf /etc/nginx/http.d/
	openssl genrsa -out /etc/ssl/private/nginx.key 2048
	openssl req -x509 -key /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt -subj /
	chown -R www-data:www-data /var/lib/nginx
	rm -f /root/reset
fi

exec "$@"
